# Generated by Django 4.2.1 on 2023-06-02 12:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notion_db", models.CharField(max_length=36)),
                ("notion_db_date_prop_id", models.CharField(max_length=32)),
                (
                    "notion_last_edit",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("g_tasks_tasklist", models.TextField(null=True)),
                ("notion_db_done_prop_id", models.CharField(max_length=32, null=True)),
                ("g_tasks_last_edit", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncedRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notion_id", models.CharField(max_length=36)),
                ("title", models.CharField(max_length=200)),
                ("date_end", models.DateTimeField(null=True)),
                (
                    "sync_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.syncconfig",
                    ),
                ),
                ("date_start", models.DateTimeField(null=True)),
                ("g_tasks_id", models.CharField(max_length=64, null=True)),
                ("done", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
