# Generated by Django 4.2.6 on 2023-10-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_syncedrecord_notion_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncconfig",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
